FROM docker.io/python:3.11.15-slim-trixie

# Install development tools
RUN apt update && apt install -y \
    curl \
    git \
    locales \
    make \
    pipx \
    ripgrep \
    ssh

# Set locales
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8

# Use --global to make package available to all users
RUN pipx install --global pdm
RUN pipx install --global rust-just
RUN pipx install --global copier && pipx inject --global copier copier-template-extensions
RUN pipx install --global git-cliff

# Setup virtual env
RUN python -m venv /venv
RUN echo "source /venv/bin/activate" >> ~/.bashrc
