FROM docker.io/python:3.11.15-slim-trixie

# Install development tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    git \
    locales \
    make \
    pipx \
    ripgrep \
    ssh \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Set locales
RUN sed -i 's/^# \(C.UTF-8 UTF-8\)/\1/' /etc/locale.gen \
 && locale-gen \
 && update-locale LANG=C.UTF-8
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# Use --global to make package available to all users
RUN pipx install --global pdm
RUN pipx install --global rust-just
RUN pipx install --global copier && pipx inject --global copier copier-template-extensions
RUN pipx install --global git-cliff

# Setup virtual env
RUN python -m venv /venv
RUN echo "source /venv/bin/activate" >> ~/.bashrc
