FROM docker.io/python:3.11.7-slim-bookworm

# Install development tools
RUN apt update && apt install -y \
    curl \
    git \
    locales \
    make \
    pipx \
    python3 \
    ripgrep \
    ssh

# Set locales
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8

ENV PIPX_BIN_DIR=/usr/bin/
RUN pipx install pdm && pipx install rust-just
RUN pipx install copier && pipx inject copier copier-template-extensions

# Setup virtual env
RUN python -m venv /venv
RUN echo "source /venv/bin/activate" >> ~/.bashrc
