FROM debian:bookworm-slim

# Install development tools
RUN apt update && apt install -y \
    curl \
    git \
    locales \
    make \
    pipx \
    ssh

# Set locales
RUN sed -i 's/^# \(C.UTF-8 UTF-8\)/\1/' /etc/locale.gen \
 && locale-gen \
 && update-locale LANG=C.UTF-8
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# Install tools
ENV PIPX_BIN_DIR=/usr/bin/
RUN pipx install rust-just
RUN pipx install copier && pipx inject copier copier-template-extensions
RUN pipx install git-cliff
RUN pipx install pre-commit
