FROM debian:bookworm-slim

# Install development tools
RUN apt update && apt install -y \
    curl \
    git \
    locales \
    make \
    pipx \
    ssh

# Set locales
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8

ENV PIPX_BIN_DIR=/usr/bin/
RUN pipx install rust-just
RUN pipx install copier && pipx inject copier copier-template-extensions
RUN pipx install git-cliff
RUN pipx install pre-commit
